### PR TITLE
fix: fix the failed after add mdoeladapter

### LINKED ISSUE #2090: Model Run Fail (ModelAdapter) Failure After Gateway-Plugin Pod Restart Due to Model Not Found Error
### 🐛 Describe the bug

When the modelAdapter is running, after the gateway-plugin pod restarts, the Model run fails with the error: Error: 

API request failed with status code 500: {"detail":"{"error":{"code":"model_not_found","message":"model name404 does not exist","param":"model","type":"invalid_request_error"}}"}

 checking the logs, it is found that instance.resyncModelAdapters(modelInformer.GetStore()) execution error log:

`W0408 07:54:20.791239       1 util.go:89] environment variable PROMETHEUS_BASIC_AUTH_PASSWORD is not set, using default value: 

E0408 07:54:20.815411       1 informers.go:302] pod inference-c4a2ddb493ce4fdfa51f6453a365b9ce-a-0 does not exist in internal-cache
E0408 07:54:20.815474       1 informers.go:302] pod inference-c4a2ddb493ce4fdfa51f6453a365b9ce-a-0 does not exist in internal-cache
E0408 07:54:20.815566       1 informers.go:302] pod inference-c4a2ddb493ce4fdfa51f6453a365b9ce-a-0 does not exist in internal-cache
E0408 07:54:20.815615       1 informers.go:302] pod inference-c4a2ddb493ce4fdfa51f6453a365b9ce-a-0 does not exist in internal-cache

I0408 07:54:21.660636       1 router.go:109] Registered router for slo
I0408 07:54:21.660707       1 router.go:109] Registered router for slo-least-load-pulling
I0408 07:54:21.660725       1 router.go:146] Registered router for slo-pack-load
I0408 07:54:21.660735       1 router.go:146] Registered router for slo-least-load

I0408 07:54:21.694338       1 informers.go:370] Resyncing ModelAdapters to ensure pod mappings are correct
E0408 07:54:21.786142       1 informers.go:323] failed to initialize model-based queue router: router did not initialized: context deadline exceeded
W0408 07:54:21.786486       1 informers.go:384] Pod inference/inference-c4a2ddb493ce4fdfa51f6453a365b9ce-a-0 not found in cache for ModelAdapter gst-123002 during resync
-1
W0408 07:54:21.786535       1 informers.go:384] Pod inference/inference-c4a2ddb493ce4fdfa51f6453a365b9ce-a-0 not found in cache for ModelAdapter name404 during resync
0
W0408 07:54:21.786550       1 informers.go:384] Pod inference/inference-c4a2ddb493ce4fdfa51f6453a365b9ce-a-0 not found in cache for ModelAdapter gy330 during resync
1
W0408 07:54:21.786561       1 informers.go:384] Pod inference/inference-c4a2ddb493ce4fdfa51f6453a365b9ce-a-0 not found in cache for ModelAdapter yhmodel1 during resync
2
I0408 07:54:21.786578       1 informers.go:392] ModelAdapter resync completed`

check pod list:
kubectl get pod  -n inference | grep c4a2ddb493ce4fdfa51f6453a365b9ce
inference-c4a2ddb493ce4fdfa51f6453a365b9ce-a-0    1/1     Running   0          94d

### Steps to Reproduce

1. aibirx 0.5.0

### Expected behavior

model run success

### Environment

1. aibirx 0.5.0

### PR DESCRIPTION
**Pull request by scarlet25151**
## Pull Request Description
This PR fixes a startup race in the gateway cache where `ModelAdapter` events can be processed before the corresponding pod has been added into the internal pod cache.

When that happens, `addModelAdapter()` fails to build the adapter-to-pod mapping, which can leave the adapter model missing from `metaModels` and cause requests to fail with `model_not_found` after gateway restart.

Changes in this PR:
- add retry logic in `resyncModelAdapters()` to wait for late pod cache population during informer initialization
- add `verifyModelAdapterMappings()` after resync to validate mapping completeness and repair missing adapter mappings when pods are already present in cache
- add regression tests covering:
  - repairing missing adapter mappings through verification
  - recovering adapter mappings when pod cache population is delayed during resync

This improves cache recovery after restart and reduces the chance of transient `model_not_found` errors for valid `ModelAdapter` models.

## Related Issues
Resolves: #2090 

**Important: Before submitting, please complete the description above and review the checklist below.**

---

<details>
<summary><strong>Contribution Guidelines (Expand for Details)</strong></summary>

<p>We appreciate your contribution to aibrix! To ensure a smooth review process and maintain high code quality, please adhere to the following guidelines:</p>

<h3>Pull Request Title Format</h3>
<p>Your PR title should start with one of these prefixes to indicate the nature of the change:</p>
<ul>
    <li><code>[Bug]</code>: Corrections to existing functionality</li>
    <li><code>[CI]</code>: Changes to build process or CI pipeline</li>
    <li><code>[Docs]</code>: Updates or additions to documentation</li>
    <li><code>[API]</code>: Modifications to aibrix's API or interface</li>
    <li><code>[CLI]</code>: Changes or additions to the Command Line Interface</li>
    <li><code>[Misc]</code>: For changes not covered above (use sparingly)</li>
</ul>
<p><em>Note: For changes spanning multiple categories, use multiple prefixes in order of importance.</em></p>

<h3>Submission Checklist</h3>
<ul>
    <li>[x] PR title includes appropriate prefix(es)</li>
    <li>[x] Changes are clearly explained in the PR description</li>
    <li>[x] New and existing tests pass successfully</li>
    <li>[x] Code adheres to project style and best practices</li>
    <li>[ ] Documentation updated to reflect changes (if applicable)</li>
    <li>[x] Thorough testing completed, no regressions introduced</li>
</ul>

<p>By submitting this PR, you confirm that you've read these guidelines and your changes align with the project's contribution standards.</p>

</details>

### CODE REVIEW

File: pkg/cache/informers.go [hunk 1]
```diff
@@ -381,29 +387,91 @@ func (c *Store) deletePodAndModelMappingLocked(podName, namespace, modelName str
...
+		}
+	}
+	klog.Infof("ModelAdapter mapping resync completed: %d total, %d complete, %d incomplete",
+		totalModels, completeModels, len(lastMissing))
 	klog.Info("ModelAdapter resync completed")
 }
+
+func waitForModelAdapterResyncRetry(stopCh <-chan struct{}, interval time.Duration) bool {
+	if stopCh == nil {
+		time.Sleep(interval)
```
Comment (Jeffwan) [inline pkg/cache/informers.go:464]: this is a little bit tricky here. while, seems it only sleep 1s which is acceptable for now

**Review by Jeffwan — APPROVED** [review]
lgtm
